#!/usr/bin/env python3
"""Daily arXiv radar for awesome-self-improving-coding-agents.

Fetches recent arXiv entries that match self-improvement / coding-agent
keyword groups and regenerates ``docs/radar.md``. Stdlib only.

Usage:
    python scripts/radar.py              # fetch live, rewrite docs/radar.md
    python scripts/radar.py --selftest   # parse+render an embedded fixture, no network
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ARXIV_API = "https://export.arxiv.org/api/query"
ATOM = "http://www.w3.org/2005/Atom"
WINDOW_DAYS = 14
MAX_PER_QUERY = 60
REPO_URL = "https://github.com/vicfei/awesome-self-improving-coding-agents"

# Keyword groups: (tag, arXiv search_query). Tune these via PR.
QUERIES: list[tuple[str, str]] = [
    (
        "self-improvement",
        'ti:"self-improving" OR ti:"self-improvement" OR ti:"self-evolving" '
        'OR ti:"recursive self-improvement"',
    ),
    (
        "agentic coding",
        '(all:"self-improving" OR all:"self-improvement" OR all:"self-evolving") '
        'AND (all:"coding agent" OR all:"code agent" OR all:"software engineering" '
        'OR all:"LLM agent")',
    ),
]

SELFTEST_FIXTURE = """<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <entry>
    <id>http://arxiv.org/abs/2609.00001v1</id>
    <title>A Self-Improving Coding Agent That Ships | pipe test</title>
    <published>2026-09-27T00:00:00Z</published>
    <arxiv:primary_category xmlns:arxiv="http://arxiv.org/schemas/atom" term="cs.SE"/>
  </entry>
  <entry>
    <id>http://arxiv.org/abs/2609.00002v1</id>
    <title>Not cs so should be filtered</title>
    <published>2026-09-26T00:00:00Z</published>
    <arxiv:primary_category xmlns:arxiv="http://arxiv.org/schemas/atom" term="physics.comp-ph"/>
  </entry>
</feed>
"""


def http_get(url: str, attempts: int = 3, timeout: int = 30) -> bytes:
    last_err: Exception | None = None
    for i in range(attempts):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "radar/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read()
        except Exception as err:  # noqa: BLE001 - retry any transport error
            last_err = err
            time.sleep(5 * (i + 1))
    raise RuntimeError(f"GET failed after {attempts} attempts: {url} ({last_err})")


def fetch_feed(tag: str, query: str) -> bytes:
    params = urllib.parse.urlencode(
        {"search_query": query, "sortBy": "submittedDate", "sortOrder": "descending", "max_results": MAX_PER_QUERY}
    )
    return http_get(f"{ARXIV_API}?{params}")


def parse_feed(tag: str, xml: bytes) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    root = ET.fromstring(xml)
    for node in root.findall(f"{{{ATOM}}}entry"):
        raw_id = (node.findtext(f"{{{ATOM}}}id") or "").strip()
        arxiv_id = raw_id.rsplit("/abs/", 1)[-1]
        # strip version suffix for a stable link, keep it in the id we display
        stable_id = arxiv_id.split("v")[0] if arxiv_id else ""
        title = " ".join((node.findtext(f"{{{ATOM}}}title") or "").split())
        published = (node.findtext(f"{{{ATOM}}}published") or "").strip()
        prim = node.find("{http://arxiv.org/schemas/atom}primary_category")
        category = prim.get("term", "") if prim is not None else ""
        if not (stable_id and title and published):
            continue
        entries.append(
            {
                "id": stable_id,
                "title": title,
                "published": published,
                "category": category,
                "tag": tag,
            }
        )
    return entries


def in_window(published: str, now: dt.datetime, days: int) -> bool:
    try:
        when = dt.datetime.fromisoformat(published.replace("Z", "+00:00"))
    except ValueError:
        return False
    return (now - when).total_seconds() <= days * 86400


def collect(now: dt.datetime) -> list[dict[str, str]]:
    seen: dict[str, dict[str, str]] = {}
    for tag, query in QUERIES:
        for e in parse_feed(tag, fetch_feed(tag, query)):
            if e["id"] in seen:
                continue
            if not e["category"].startswith("cs."):
                continue
            if not in_window(e["published"], now, WINDOW_DAYS):
                continue
            seen[e["id"]] = e
    return sorted(seen.values(), key=lambda e: e["published"], reverse=True)


def render(entries: list[dict[str, str]], now: dt.datetime) -> str:
    lines = [
        "<!-- Auto-generated by scripts/radar.py via GitHub Actions. Manual edits will be overwritten. -->",
        "# 🤖 arXiv Radar",
        "",
        f"Papers from the last **{WINDOW_DAYS} days** matching this repo's "
        f"[keyword groups](../scripts/radar.py). Refreshed daily — "
        f"generated {now.strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
    ]
    if not entries:
        lines += ["_No matches in the current window. Quiet fortnight — or tune the keywords via a PR._", ""]
    else:
        n = len(entries)
        lines += [f"**{n} paper{'s' if n != 1 else ''}** spotted.", "", "| Date | Paper | Areas | Matched |", "|---|---|---|---|"]
        for e in entries:
            date = e["published"][:10]
            title = e["title"].replace("|", "\\|")
            lines.append(
                f"| {date} | [{title}](https://arxiv.org/abs/{e['id']}) | {e['category']} | {e['tag']} |"
            )
    lines += [
        "",
        "---",
        "",
        f"Hand-curated sections live in the [main README](../README.md). "
        f"Keywords are defined at the top of [`scripts/radar.py`](../scripts/radar.py) — PRs welcome.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    now = dt.datetime.now(dt.timezone.utc)
    entries = collect(now)
    out = Path(__file__).resolve().parent.parent / "docs" / "radar.md"
    out.write_text(render(entries, now), encoding="utf-8")
    print(f"radar: wrote {len(entries)} entries -> {out}")
    return 0


def selftest() -> int:
    now = dt.datetime(2026, 9, 28, tzinfo=dt.timezone.utc)
    entries = parse_feed("test", SELFTEST_FIXTURE.encode())
    kept = [e for e in entries if e["category"].startswith("cs.")]
    assert len(entries) == 2, f"expected 2 parsed entries, got {len(entries)}"
    assert len(kept) == 1 and kept[0]["id"] == "2609.00001", f"cs.* filter failed: {kept}"
    md = render(kept, now)
    assert "pipe test" in md and "\\|" in md, "pipe escaping failed"
    assert "2609.00001" in md and "physics" not in md, "render content wrong"
    print("selftest OK — parse, category filter, dedupe-ready structure, pipe escaping, render:")
    print(md)
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true", help="run offline fixture test")
    args = ap.parse_args()
    sys.exit(selftest() if args.selftest else main())
